### PR TITLE
4734 - Article rename race condition fix

### LINKED ISSUE #4734: Article Renaming race conditions
Reproduction Steps:
1. From transcribe, create a subject (this will create an article)
2. Edit article name
3. While rename job is running (and without reloading transcribe page), make another change to the source text and click save
  - This will create race condition on the page, which dettaches the page_article_links and creates new article.

Proposed solution is to consider finding article matches based on previous versions created within the hour before deciding if we are dealing with renamed articles or not.

### PR DESCRIPTION
**Pull request by WillNigel23**

### CODE REVIEW

File: app/models/xml_source_processor.rb [hunk 1]
```diff
@@ -345,34 +345,55 @@ def update_links_and_xml(xml_string, preview_mode=false, text_type)
     # first clear out the existing links
     # log the count of articles before and after
     clear_links(text_type) unless preview_mode
-    processed = ""
+
+    candidate_articles = collection.articles.left_joins(:article_versions)
```
Comment (benwbrum) [inline app/models/xml_source_processor.rb:349]: I'm not sure why we're joining `articles` to `article_versions` here, since we don't appear to use it below.

File: app/models/xml_source_processor.rb [hunk 2]
```diff
@@ -345,34 +345,55 @@ def update_links_and_xml(xml_string, preview_mode=false, text_type)
...
 
+      article = candidate_articles.find_by(title: title)
+
+      if article.nil?
+        article_version = ArticleVersion.where(article_id: candidate_articles.select(:id))
+                                        .where(title: title)
+                                        .where('created_on > ?', page_update_timestamp)
+                                        .order(created_on: :desc)
+                                        .first
+        article = article_version&.article
```
Comment (benwbrum) [inline app/models/xml_source_processor.rb:377]: I think that we might be able to use the left join above here by doing something like this:
```ruby
candidate_articles.where('article_versions.title': title)
                                 .where(where('article_versions.created_on > ?', page_update_timestamp)
```
etc.  

It's possible that in that case we'd get the correct article, rather than having to pluck it from the article_version, since it would already be in the join.

**Review by benwbrum — CHANGES_REQUESTED** [review]
I really love this approach.  Minor changes requestd.

File: app/models/xml_source_processor.rb (hunk 1 above)
Comment (WillNigel23) [reply app/models/xml_source_processor.rb:349]: Forgot to remove this one.

**Comment by benwbrum** [comment]
I'm not quite sure why this didn't work, but here's what I did:
* Brought up a collection `khs/cwgk-migration` that had thousands of pages and edited `Commonwealth of Kentucky` which had hundreds of pages mention it
* Changed the title to `State of Kentucky`.
* Clicked the Overview tab of the article
* Clicked on the bottom page of in the listing on the right side
* The Page Overview had a mousover (drawn from the `title` attribute of `Commonwealth of Kentucky`, indicating that the XML text was still not updated
* The Tooltip pop-up showed `State of Kentucky`, indicating that the title of the subject article was the new title
* Click the Transcription screen
* See `[[Commonwealth of Kentucky|Ky]]` in the text, indicating that the `source_text` has not been updated.
* Hit Save and got this:
Screenshot from 2025-07-03 18-20-18

**Comment by benwbrum** [comment]
This shows the same behavior as my previous test.  If I change the title of a subject, then save a page that hasn't been updated yet, it still prompts me to categorize a new-looking subject with the old title.

**Comment by benwbrum** [comment]
see also #4662

**Comment by saracarl** [comment]
This is affecting WWP, CWRGM, and Dartmouth.

**Comment by benwbrum** [comment]
I finally was able to get a reproduction video!

https://github.com/user-attachments/assets/eace40b4-4682-4347-95de-8a462392743c
